on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.0.x'
          
      - name: Build projectElra6
        run: dotnet build ./projectElra6
        
      - name: Build projectElra25
        run: dotnet build ./projectElra25

      - name: Set DOTNET_ROLL_FORWARD
        run: echo "DOTNET_ROLL_FORWARD=latestMajor" >> $GITHUB_ENV
      - name: Lint (Elra6)
        run: |
          dotnet tool install -g dotnet-fsharplint
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          dotnet fsharplint lint ./projectElra6
      - name: Lint (Elra25)
        run: |
          dotnet tool install -g dotnet-fsharplint
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          dotnet fsharplint lint ./projectElra25
      - name: Formatter (Elra6)
        run: |
          dotnet tool install -g fantomas-tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          fantomas ./projectElra6/*.fs 

      - name: Formatter (Elra25)
        run: |
          dotnet tool install -g fantomas-tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          fantomas ./projectElra25/*.fs 
    
      
        
      - name: Run projectElra6
        run: dotnet run --project ./projectElra6

      - name: Run projectElra25
        run: dotnet run --project ./projectElra25


      - name: Tests
        run: |
            dotnet restore ProjectTests/ProjectTests.fsproj
            dotnet build ./ProjectTests
            dotnet test ./ProjectTests
